# Generated by Django 4.2.7 on 2025-03-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='about_email_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='about_requirement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
