# Generated by Django 4.2.7 on 2025-02-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
