# Generated by Django 4.2.7 on 2025-03-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_about_us_about_email_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('error_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'error_log',
            },
        ),
    ]
