# Generated by Django 4.2.7 on 2025-02-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_chatbot_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='link',
        ),
    ]
