# Generated by Django 4.2.7 on 2025-04-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_error_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_notification',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.TextField(blank=True, null=True)),
                ('event_name', models.TextField(blank=True, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events_notification',
            },
        ),
    ]
