# Generated by Django 4.2.7 on 2025-02-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_chatbot_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='id',
            new_name='sr_no',
        ),
    ]
