# Generated by Django 4.2.7 on 2025-02-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_id_contact_us_sr_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us',
            new_name='contact',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
