# Generated by Django 4.2.7 on 2025-03-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_webiste_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='mobile_no',
        ),
    ]
