# Generated by Django 4.2.7 on 2025-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_contact_us_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('about_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_full_name', models.TextField(blank=True, null=True)),
                ('about_email_id', models.TextField(blank=True, null=True)),
                ('about_budget', models.TextField(blank=True, null=True)),
                ('about_requirement', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_us',
            },
        ),
    ]
