# Generated by Django 4.2.7 on 2025-03-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='about_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
